# Generated by Django 5.1.4 on 2026-09-20 07:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shipments', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_type', models.CharField(choices=[('full', 'Full return'), ('partial', 'Partial return'), ('exchange', 'Exchange')], default='full', max_length=20)),
                ('reason', models.CharField(choices=[('customer_refused', 'Customer refused delivery'), ('wrong_item', 'Wrong item sent'), ('damaged', 'Damaged in transit'), ('size_issue', 'Size or fit issue'), ('not_available', 'Customer not available'), ('quality', 'Quality not as expected'), ('fake_order', 'Fake order'), ('other', 'Other')], max_length=30)),
                ('reason_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received back'), ('resolved', 'Resolved')], default='initiated', max_length=20)),
                ('forward_delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('return_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('written_off_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='shipments.shipment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'returns_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('sellable', 'Sellable'), ('damaged', 'Damaged')], default='sellable', max_length=20)),
                ('restocked', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.orderitem')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
            ],
            options={
                'db_table': 'returns_return_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['store', 'status'], name='returns_ret_store_i_1a2223_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['store', 'reason'], name='returns_ret_store_i_caa325_idx'),
        ),
    ]
