# Generated by Django 5.1.4 on 2026-09-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('new_public_order', 'New order from the public form'), ('low_stock', 'Low stock'), ('cod_overdue', 'COD overdue'), ('booking_failed', 'Courier booking failed'), ('return_recorded', 'Return recorded'), ('settlement_committed', 'Settlement committed'), ('order_cancelled', 'Order cancelled')], max_length=30)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Needs attention'), ('critical', 'Urgent')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['store', 'is_read', '-created_at'], name='notificatio_store_i_6b31ae_idx'), models.Index(fields=['store', 'notification_type'], name='notificatio_store_i_b76cd8_idx')],
            },
        ),
    ]
