# Generated by Django 5.1.4 on 2026-09-20 07:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('ad_spend', 'Ad spend'), ('packaging', 'Packaging'), ('salary', 'Salary'), ('rent', 'Rent'), ('courier_charge', 'Courier charge'), ('product_purchase', 'Product purchase'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('campaign_name', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'expenses_expense',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['store', '-date'], name='expenses_ex_store_i_602641_idx'), models.Index(fields=['store', 'category'], name='expenses_ex_store_i_2cfa98_idx')],
            },
        ),
    ]
