# Generated by Django 5.1.4 on 2026-09-19 08:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=32)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('shipping_district', models.CharField(max_length=60)),
                ('shipping_thana', models.CharField(blank=True, max_length=60)),
                ('shipping_area', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(choices=[('messenger', 'Facebook Messenger'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call'), ('comment', 'Facebook comment'), ('public_form', 'Public order form'), ('manual', 'Manual entry')], default='manual', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('internal_note', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('confirmation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_call_outcome', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('no_answer', 'No answer'), ('call_later', 'Asked to call later'), ('cancelled', 'Cancelled'), ('fake', 'Fake order')], max_length=20)),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('customer_cancelled', 'Customer cancelled'), ('fake_order', 'Fake or prank order'), ('unreachable', 'Customer unreachable'), ('out_of_stock', 'Out of stock'), ('duplicate', 'Duplicate order'), ('price_dispute', 'Price disagreement'), ('other', 'Other')], max_length=30)),
                ('cancel_note', models.CharField(blank=True, max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'orders_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('on_hold', 'On Hold')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('on_hold', 'On Hold')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'orders_status_history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', '-created_at'], name='orders_orde_store_i_510e34_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', '-created_at'], name='orders_orde_store_i_6d7de7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'customer'], name='orders_orde_store_i_bfe4ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('store', 'order_number'), name='uniq_store_order_number'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_stat_order_i_2c4cd1_idx'),
        ),
    ]
