# Generated by Django 5.1.4 on 2026-09-21 11:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order_limit', models.PositiveIntegerField(blank=True, help_text='Orders per billing period. Blank means unlimited.', null=True)),
                ('staff_limit', models.PositiveSmallIntegerField(default=1)),
                ('courier_limit', models.PositiveSmallIntegerField(default=1)),
                ('sms_credits', models.PositiveIntegerField(default=0)),
                ('allows_api_courier', models.BooleanField(default=False)),
                ('allows_analytics', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('period_start', models.DateField(default=django.utils.timezone.localdate)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('orders_used', models.PositiveIntegerField(default=0)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
            options={
                'db_table': 'billing_subscription',
            },
        ),
    ]
