# Generated by Django 5.1.4 on 2026-09-19 18:23

import apps.core.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('adapter_key', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='couriers/')),
                ('supports_api', models.BooleanField(default=False)),
                ('supports_webhook', models.BooleanField(default=False)),
                ('supports_quote', models.BooleanField(default=False)),
                ('supports_cancel', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'couriers_courier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', apps.core.encryption.EncryptedJSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_links', to='couriers.courier')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'couriers_store_courier',
                'ordering': ['-is_default', 'courier__name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'courier'), name='uniq_store_courier')],
            },
        ),
    ]
