# Generated by Django 5.1.4 on 2026-09-18 12:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('facebook_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('high_risk', 'High Risk'), ('blacklisted', 'Blacklisted')], default='good', max_length=20)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.CharField(blank=True, max_length=200)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('returned_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('division', models.CharField(blank=True, max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('thana', models.CharField(blank=True, max_length=60)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'customers_address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', 'risk_level'], name='customers_c_store_i_736b07_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', '-last_order_at'], name='customers_c_store_i_144863_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('store', 'phone'), name='uniq_store_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'is_default'], name='customers_a_custome_d08d94_idx'),
        ),
    ]
