# Generated by Django 5.1.4 on 2026-09-20 07:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0002_seed_couriers'),
        ('orders', '0001_initial'),
        ('shipments', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_reference', models.CharField(blank=True, max_length=120)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='settlements/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
                ('store_courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='couriers.storecourier')),
            ],
            options={
                'db_table': 'payments_courier_settlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer'), ('cash', 'Cash in hand'), ('other', 'Other')], max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Paid out')], default='in', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('consignment_id', models.CharField(blank=True, max_length=100)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deducted_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'No shipment found'), ('amount_mismatch', 'Amount differs'), ('already_settled', 'Already settled')], default='unmatched', max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.couriersettlement')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='shipments.shipment')),
            ],
            options={
                'db_table': 'payments_settlement_line',
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='couriersettlement',
            index=models.Index(fields=['store', 'status'], name='payments_co_store_i_e97951_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['store', '-received_at'], name='payments_pa_store_i_f591f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['store', 'method'], name='payments_pa_store_i_63bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementline',
            index=models.Index(fields=['settlement', 'match_status'], name='payments_se_settlem_93531b_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementline',
            index=models.Index(fields=['consignment_id'], name='payments_se_consign_719021_idx'),
        ),
    ]
