# Generated by Django 5.1.4 on 2026-09-18 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('business_type', models.CharField(choices=[('fashion', 'Fashion & Clothing'), ('electronics', 'Electronics & Gadgets'), ('beauty', 'Beauty & Cosmetics'), ('food', 'Food & Grocery'), ('home', 'Home & Living'), ('baby', 'Baby & Kids'), ('other', 'Other')], default='other', max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('facebook_page_url', models.URLField(blank=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=60)),
                ('order_prefix', models.CharField(default='ORD', max_length=8)),
                ('order_sequence', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores_store',
                'ordering': ['-created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_charge_inside_dhaka', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delivery_charge_outside_dhaka', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('district_charge_overrides', models.JSONField(blank=True, default=dict)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order subtotal at or above which delivery is free. Blank = never.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_header', models.CharField(blank=True, max_length=200)),
                ('invoice_footer_note', models.TextField(blank=True)),
                ('invoice_terms', models.TextField(blank=True)),
                ('show_discount_on_invoice', models.BooleanField(default=True)),
                ('sms_on_confirmed', models.BooleanField(default=False)),
                ('sms_on_shipped', models.BooleanField(default=False)),
                ('sms_on_delivered', models.BooleanField(default=False)),
                ('fraud_return_count_threshold', models.PositiveSmallIntegerField(default=3)),
                ('fraud_return_rate_threshold', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Percent. Return rate at or above this flags the customer.', max_digits=5)),
                ('cod_overdue_days', models.PositiveSmallIntegerField(default=7)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'store settings',
                'db_table': 'stores_settings',
            },
        ),
        migrations.CreateModel(
            name='StoreInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('order_staff', 'Order Staff'), ('delivery_staff', 'Delivery Staff'), ('accountant', 'Accountant')], default='order_staff', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='stores.store')),
            ],
            options={
                'db_table': 'stores_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'email'], name='stores_invi_store_i_b6105f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('order_staff', 'Order Staff'), ('delivery_staff', 'Delivery Staff'), ('accountant', 'Accountant')], default='order_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memberships', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='stores_memb_user_id_0ad249_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='uniq_store_user_membership')],
            },
        ),
    ]
