# Generated by Django 5.1.4 on 2026-09-19 18:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment_id', models.CharField(db_index=True, max_length=100)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('booking_mode', models.CharField(choices=[('api', 'Booked via courier API'), ('manual', 'Entered manually')], default='manual', max_length=10)),
                ('quoted_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cod_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending collection'), ('collected', 'Collected by courier'), ('settled', 'Settled to seller')], default='pending', max_length=20)),
                ('cod_collected_at', models.DateTimeField(blank=True, null=True)),
                ('cod_settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=120)),
                ('current_courier_status', models.CharField(blank=True, max_length=80)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_failures', models.PositiveSmallIntegerField(default=0)),
                ('raw_booking_request', models.JSONField(blank=True, default=dict)),
                ('raw_booking_response', models.JSONField(blank=True, default=dict)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
                ('store_courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='couriers.storecourier')),
            ],
            options={
                'db_table': 'shipments_shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_status', models.CharField(max_length=80)),
                ('mapped_status', models.CharField(blank=True, max_length=30)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(default='poll', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipments.shipment')),
            ],
            options={
                'db_table': 'shipments_delivery_status_history',
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['store', 'cod_status'], name='shipments_s_store_i_402356_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['store', '-created_at'], name='shipments_s_store_i_9261b4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['consignment_id'], name='shipments_s_consign_dfb1bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('store_courier', 'consignment_id'), name='uniq_courier_consignment'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['shipment', '-observed_at'], name='shipments_d_shipmen_e82c43_idx'),
        ),
    ]
